project_id = "cvccrvyimyzrxcwzmxwk"

[functions.generate-fitness-plan]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-personal-training-request]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.generate-workout-image]
verify_jwt = false

[functions.generate-program-image]
verify_jwt = false
