project_id = "cvccrvyimyzrxcwzmxwk"

[functions.smarty-coach]
verify_jwt = false

[functions.generate-fitness-plan]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-personal-training-request]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.generate-workout-image]
verify_jwt = false

[functions.create-individual-purchase-checkout]
verify_jwt = true

[functions.verify-purchase]
verify_jwt = false

[functions.generate-program-image]
verify_jwt = false

[functions.send-renewal-reminders]
verify_jwt = false

[functions.send-reengagement-emails]
verify_jwt = false

[functions.send-scheduled-notifications]
verify_jwt = false

[functions.delete-stripe-product]
verify_jwt = false
